[package]
name = "sandbox"
version = "0.1.0"
authors = ["ban-m <ban-m@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poa_hmm = {path = "../partial_order_alignment"}
rand = "*"
rand_xoshiro = "*"